# Generated by Django 4.1.7 on 2023-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
