# Generated by Django 4.1.7 on 2023-07-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_address_history_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='status',
            new_name='active',
        ),
    ]
